server:
  port: 80
token:
  signing:
    access-token: ${AUTH_ACCESS_TOKEN:8tyGvQ0pzPcvsrA8O8YAh2idUrN07W6t2bolCim2c4E=}
    refresh-token: ${AUTH_REFRESH_TOKEN:5N9kotyNMUI/WDh7/B27+1MOZUYGcFZcdwmUmiyiGEQ=}
spring:
  application:
    name: gateway-api-service
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: http://${PROFILE_SERVICE:localhost}:8081
          predicates:
            - Path=/profiles/**, /profiles, /bios/**, /bios, /preferences/**, /preferences
          filters:
            - RewritePath=/profiles(?<segment>.*), /api/v1/profiles${segment}
            - RewritePath=/bios(?<segment>.*), /api/v1/bios${segment}
            - RewritePath=/preferences(?<segment>.*), /api/v1/preferences${segment}
            - name: AuthFilter
        - id: auth-service
          uri: http://${AUTH_SERVICE:localhost}:81
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/v1/auth/${segment}
        - id: recommendation-service
          uri: http://${RECOMMENDATION_SERVICE:localhost}:8082
          predicates:
            - Path=/recommendations, /preferences
          filters:
            - RewritePath=/recommendations, /api/v1/recommendations
            - name:
                AuthFilter
        - id: location-service
          uri: http://${LOCATION_SERVICE:localhost}:8083
          predicates:
            - Path=/locations/**, /locations
          filters:
            - RewritePath=/locations(?<segment>.*), /api/v1/locations/${segment}
            - name:
                AuthFilter
        - id: matcher-service
          uri: http://${MATCHER_SERVICE:localhost}:8084
          predicates:
            - Path=/likes**, /likes, /likes/**
          filters:
            - RewritePath=/likes(?<segment>.*), /api/v1/likes${segment}
            - name:
                AuthFilter
