server:
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    url: ${PROFILE_DB_URL:jdbc:postgresql://localhost:5432/profile_database}
    username: ${PROFILE_DB_USER:postgres}
    password: ${PROFILE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

location:
  command:
    topic: locations-command
recommendation:
  command:
    topic: recommendations-command


grpc:
  server:
    port: 9899