server:
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    url: ${PROFILE_DB_URL:jdbc:postgresql://localhost:5432/profile_database}
    username: ${PROFILE_DB_USER:postgres}
    password: ${PROFILE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      group-id: profile-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

location:
  command:
    topic: locations-command
recommendation:
  command:
    topic: recommendations-command


grpc:
  server:
    port: 9899