server:
  port: 8082
spring:
  application:
    name: recommendation-service
  datasource:
    url: ${RECOMMENDATION_DB_URL:jdbc:postgresql://localhost:5432/recommendation_database}
    username: ${RECOMMENDATION_DB_USER:postgres}
    password: ${RECOMMENDATION_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
        allow.auto.create.topics: false
    consumer:
      group-id: recommendation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: ru.bogdsvn.kafka_library.*

recommendation:
  command:
    topic: recommendations-command
  event:
    topic: recommendations-event

grpc:
  client:
    location-service:
      address: ${LOCATION_SERVICE:localhost}:9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    profile-service:
      address: ${PROFILE_SERVICE:localhost}:9899
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

