server:
  port: 81
spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth_database}
    username: ${AUTH_DB_USER:postgres}
    password: ${AUTH_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
token:
  signing:
    access-token: ${AUTH_ACCESS_TOKEN:8tyGvQ0pzPcvsrA8O8YAh2idUrN07W6t2bolCim2c4E=}
    refresh-token: ${AUTH_REFRESH_TOKEN:5N9kotyNMUI/WDh7/B27+1MOZUYGcFZcdwmUmiyiGEQ=}
  expiration:
    access-token: 900000
    refresh-token: 2592000000
