server:
  port: 8083
spring:
  application:
    name: location-service
  datasource:
    url: jdbc:postgresql://localhost:5432/location_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
grpc:
  server:
    port: 9898
