server:
  port: 8083
spring:
  application:
    name: location-service
  datasource:
    url: ${LOCATION_DB_URL:jdbc:postgresql://localhost:5432/location_database}
    username: ${LOCATION_DB_USER:postgres}
    password: ${LOCATION_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
grpc:
  server:
    port: 9898